# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jonashackt.github.io
email: jonas.hecht[at]codecentric.de
description: > # this means to ignore newlines until "baseurl:"
  Spring Boot & <a href="https://opensourcecontributo.rs/user/jonashackt" target="_blank">Open Source</a> guy working @ <a href="https://www.codecentric.de/ueber-uns/team/profil/?profil=jonas-hecht" target="_blank">codecentric</a>; loving Ansible, Java, Docker, Continuous Delivery; <a href="https://www.strava.com/athletes/16787462" target="_blank">Mountainbiker</a>, Dad, maintainer of <a href="https://github.com/codecentric/cxf-spring-boot-starter" target="_blank">cxf-spring-boot-starter</a>

  <iframe width="200" height="112" src="https://www.youtube.com/embed/9F-qC2XFyAE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonashackt
github_username:  jonashackt

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal #jekyll-theme-merlot #jekyll-theme-slate #jekyll-theme-architect #jekyll-theme-architect #jekyll-theme-midnight #jekyll-theme-minimal 
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
