# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jonashackt.github.io
email: jonas.hecht[at]codecentric.de
description: > # this means to ignore newlines until "baseurl:"
  Simple page about Jonas Hecht (jonashackt) - these Spring Boot guy, that loves Ansible & is a CI/CD enthusiast. 
  He´s building more & more with Docker & Spring Cloud.
  Have been SOA architect & quit the job after successful implementing inside whole company.  
  Why? Because those are just concepts - name it SOA, Microservice, Patterns, SCS, or "really cool new thingy to do". 
  But nearly no organization follows - Culture eat´s software architecture for breakfast!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonashackt
github_username:  jonashackt

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
